### ISSUE TITLE
Login App bug check

### ISSUE THREAD

**Issue by ph8tel** [Danger-Will-Robinson/mariner#14]
I need you guys to log in to app please. I can only test my two gmail accounts. It is working for both, but not sure about others. Cheers!
@writetoalexander @BigWidowsPeak

**Comment by BigWidowsPeak** [comment]
Logged in with my account, and it actually puts undefined in the users table:

<img width="224" alt="screen shot 2018-03-15 at 11 53 21 am" src="https://user-images.githubusercontent.com/22270220/37485034-8f84fed4-2847-11e8-8fe5-6dc631ae2e18.png">

I feel like something odd is happening since my channel shows my full name instead of a handle. It did successfully post my comment and show my name in the author column of the comments table however...

**Comment by BigWidowsPeak** [comment]
Resolved by #34
